Repository googleapis/python-monitoring-dashboards, pull requests merged in 2021-04, with the labels that each got.

#51 chore: start tracking obsolete files
  synth.metadata
Labels: api: monitoring, cla: yes, context: full

#52 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#53 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: monitoring, cla: yes, context: full, samples

#54 chore: prevent normalization of semver versioning
  setup.py
Labels: api: monitoring, cla: yes

#55 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#57 chore(revert): revert preventing normalization
  setup.py
Labels: api: monitoring, cla: yes
